### PR TITLE
feat: add snowtrace for Avalanche and Fuji

### PR DESCRIPTION
**Pull request by roderik**
Added the new Snowtrace Etherscan version for Avalanche.

### CODE REVIEW

**Comment by krzkaczor** [comment]
@roderik thanks for this! Can you re-run `yarn test:fix`?

**Comment by roderik** [comment]
done, I did the original changes via the GitHub web vscode

**Comment by krzkaczor** [comment]
Thanks! Merged!

**Comment by krzkaczor** [comment]
Released as: https://github.com/dethcrypto/eth-sdk/releases/tag/%40dethcrypto/eth-sdk%400.2.1

**Pull request merged**
